name: Build
on:
  workflow_dispatch:
jobs:
  buildmac:
    runs-on: macos-10
    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run:
        cd src && npm install && npm run buildmac
    - name: Upload File
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: dist/*dmg
